In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent = ['the glass of milk',
        'the glass of juice',
        'the cup of tea',
        'I am a good boy',
        'I am a good developer',
        'understand the meaning of words',
        'your videos are good']

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
vocab_size = 10000

In [5]:
## One Hot Representation
one_hot_repr = [one_hot(words,vocab_size) for words in sent]
one_hot_repr

[[3938, 1000, 193, 6342],
 [3938, 1000, 193, 6435],
 [3938, 340, 193, 8933],
 [7290, 8838, 4906, 1379, 655],
 [7290, 8838, 4906, 1379, 7737],
 [6685, 3938, 7405, 193, 3414],
 [2651, 3048, 9402, 1379]]

In [6]:
## Word Embedding Representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
# from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np

In [8]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr,padding='post',maxlen=sent_length)
print(embedded_docs)

[[3938 1000  193 6342    0    0    0    0]
 [3938 1000  193 6435    0    0    0    0]
 [3938  340  193 8933    0    0    0    0]
 [7290 8838 4906 1379  655    0    0    0]
 [7290 8838 4906 1379 7737    0    0    0]
 [6685 3938 7405  193 3414    0    0    0]
 [2651 3048 9402 1379    0    0    0    0]]


In [9]:
## feature representation using embedding
dim = 10

In [10]:
model = Sequential()
model.add(Embedding(vocab_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [11]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [12]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 268ms/step


array([[[-8.3683245e-03,  4.7243204e-02,  2.0776320e-02, -1.1661004e-02,
         -4.9083345e-03, -8.5993186e-03, -4.2927194e-02,  5.7355165e-03,
         -3.1588972e-02,  3.8043689e-02],
        [-4.9835455e-02,  1.4078770e-02, -2.2366755e-03, -2.6786685e-02,
          3.7174191e-02,  3.3787493e-02,  3.6796484e-02,  4.7426824e-02,
         -6.6828355e-03,  2.9935751e-02],
        [ 1.1556815e-02, -1.8751845e-03,  2.6694607e-02,  3.0544091e-02,
         -2.6015198e-02, -4.1237641e-02, -4.5787003e-02,  2.2465717e-02,
          4.6519469e-02,  4.6777081e-02],
        [ 3.8263489e-02,  2.7187649e-02,  3.9148379e-02,  4.1451957e-02,
         -3.1456985e-02, -3.0688966e-02,  1.2769487e-02, -4.1236699e-02,
         -7.8058951e-03,  4.4388358e-02],
        [-8.3624721e-03, -1.6948916e-02, -7.2776563e-03,  4.4301603e-02,
         -3.2560483e-02,  1.6888592e-02, -3.6316205e-02,  6.6463724e-03,
          3.5300586e-02,  1.0557711e-02],
        [-8.3624721e-03, -1.6948916e-02, -7.2776563e-03,  4.

In [13]:
embedded_docs[0]

array([3938, 1000,  193, 6342,    0,    0,    0,    0])